language: c

os: linux

matrix:
  include:
  - name: "GCC Debug"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
          - python3
          - python3-pip
    before_script:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - pip3 install meson
      - source $HOME/.cargo/env
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make

  - name: "GCC Release"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
          - python3
          - python3-pip
    before_script:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - pip3 install meson
      - source $HOME/.cargo/env
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make

  - name: "Clang Debug"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
          - python3
          - python3-pip
    before_script:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - pip3 install meson
      - source $HOME/.cargo/env
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make

  - name: "Clang Release"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
          - ninja-build
          - python3
          - python3-pip
    before_script:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - pip3 install meson
      - source $HOME/.cargo/env
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make
