language: c

os: linux

matrix:
  include:
  - name: "GCC Debug"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
          - meson
          - ninja
          - rust
    before_script:
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make

  - name: "GCC Release"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
          - meson
          - ninja
          - rust
    before_script:
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make

  - name: "Clang Debug"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
          - meson
          - ninja
          - rust
    before_script:
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make

  - name: "Clang Release"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
          - meson
          - ninja
          - rust
    before_script:
      - cd ext
      - bash aom.cmd
      - bash dav1d.cmd
      - bash rav1e.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DAVIF_CODEC_AOM=1 -DAVIF_LOCAL_AOM=1 -DAVIF_CODEC_DAV1D=1 -DAVIF_LOCAL_DAV1D=1 -DAVIF_CODEC_RAV1E=1 -DAVIF_LOCAL_RAV1E=1 ..
    script:
      - make
